name: PlatformIO CI with Wokwi

on: [push]

jobs:
  platformio:
    name: Wokwi Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh

      - name: Wokwi Simulation
        run: wokwi-cli Wokwi/Pametno zvono i pametna brava --timeout 120
        env:
          WOKWI_GITHUB_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}