name: Wokwi CI for Smart Doorbell

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh
        env:
          WOKWI_CLI_INSTALL_DIR: ${{ github.workspace }}/.local/bin
      
      - name: Add Wokwi CLI to PATH
        run: echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH

      - name: Verify project structure
        run: |
          ls -la "Wokwi/Pametno zvono i pametna brava"
          ls -la "Wokwi/Pametno zvono i pametna brava/src"

      - name: Run Wokwi simulation
        working-directory: ./Wokwi/Pametno zvono i pametna brava
        run: |
          wokwi --version
          wokwi validate
          wokwi simulate --timeout 120
        env:
          WOKWI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}