name: ESP32 CI with PlatformIO Build and Wokwi Simulation

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup PlatformIO Core
      - name: Install PlatformIO Core
        uses: platformio/action-install-platformio@v1
      
      # Install required platform
      - name: Install ESP32 Platform
        run: |
          pio platform install espressif32
          pio lib install "Keypad"
          pio lib install "ESP32Servo"

      # Build the project
      - name: Build with PlatformIO
        run: |
          pio run -e esp32doit-devkit-v1
          
      # Run Wokwi simulation
      - name: Run Wokwi Simulation
        uses: wokwi/wokwi-ci@v1
        with:
          api-key: ${{ secrets.WOKWI_CLI_TOKEN }}
          diagram: Wokwi/Pametno\ zvono\ i\ pametna\ brava/wokwi.toml
          timeout: 120
          elf: .pio/build/esp32doit-devkit-v1/firmware.elf

      # Upload simulation results
      - name: Upload simulation results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: wokwi-simulation-results
          path: wokwi-results.json
