name: Wokwi CI for Smart Doorbell

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wokwi CLI
        run: |
          mkdir -p ~/.local/bin
          curl -L https://wokwi.com/ci/install.sh | sh -s -- -b ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "PATH after addition: $PATH"
          which wokwi || ls -la ~/.local/bin

      - name: Verify installation
        run: |
          wokwi --version
          echo "Current PATH: $PATH"

      - name: Run Wokwi simulation
        working-directory: ./Wokwi/Pametno zvono i pametna brava
        run: |
          wokwi validate
          wokwi simulate --timeout 120
        env:
          WOKWI_GITHUB_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}