name: Wokwi CI for Smart Doorbell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Wokwi CLI
        run: pip install wokwi

      - name: Verify project structure
        run: |
          ls -la "Wokwi/Pametno zvono i pametna brava"
          ls -la "Wokwi/Pametno zvono i pametna brava/src"

      - name: Run Wokwi simulation
        working-directory: ./Wokwi/Pametno zvono i pametna brava
        run: |
          wokwi validate
          wokwi simulate --timeout 120
        env:
          WOKWI_GITHUB_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}