name: PlatformIO CI with Wokwi

on: [push]

jobs:
  platformio:
    name: Wokwi Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: Wokwi\Pametno zvono i pametna brava # directory with wokwi.toml, relative to repo's root